// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/shipwright/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Shipwright) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Shipwright) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func (r Plan) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source        *dagger.Directory
		Build         any
		Test          any
		Artifact      any
		ArtifactRef   string
		ArtifactCreds *dagger.Secret
		Deploy        any
		Environment   string
		DeployCreds   *dagger.Secret
		Run           any
	}
	concrete.Source = r.Source
	concrete.Build = r.Build
	concrete.Test = r.Test
	concrete.Artifact = r.Artifact
	concrete.ArtifactRef = r.ArtifactRef
	concrete.ArtifactCreds = r.ArtifactCreds
	concrete.Deploy = r.Deploy
	concrete.Environment = r.Environment
	concrete.DeployCreds = r.DeployCreds
	concrete.Run = r.Run
	return json.Marshal(&concrete)
}

func (r *Plan) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source        *dagger.Directory
		Build         *builderImpl
		Test          *testerImpl
		Artifact      *artifactorImpl
		ArtifactRef   string
		ArtifactCreds *dagger.Secret
		Deploy        *deployerImpl
		Environment   string
		DeployCreds   *dagger.Secret
		Run           *runnerImpl
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.Build = concrete.Build.toIface()
	r.Test = concrete.Test.toIface()
	r.Artifact = concrete.Artifact.toIface()
	r.ArtifactRef = concrete.ArtifactRef
	r.ArtifactCreds = concrete.ArtifactCreds
	r.Deploy = concrete.Deploy.toIface()
	r.Environment = concrete.Environment
	r.DeployCreds = concrete.DeployCreds
	r.Run = concrete.Run.toIface()
	return nil
}

type artifactorImpl struct {
	query   *querybuilder.Selection
	id      *dagger.ID
	publish *string
}

func (r *artifactorImpl) WithGraphQLQuery(q *querybuilder.Selection) Artifactor {
	return &artifactorImpl{query: q}
}

func (r *artifactorImpl) XXX_GraphQLType() string {
	return "ShipwrightArtifactor"
}

func (r *artifactorImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *artifactorImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *artifactorImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *artifactorImpl) UnmarshalJSON(bs []byte) error {
	var id dagger.ID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = artifactorImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("ShipwrightArtifactor")}
	return nil
}

func (r *artifactorImpl) toIface() Artifactor {
	if r == nil {
		return nil
	}
	return r
}

func (r *artifactorImpl) ID(ctx context.Context) (dagger.ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response dagger.ID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *artifactorImpl) Publish(ctx context.Context, build *dagger.Directory, ref string, creds *dagger.Secret) (string, error) {
	if r.publish != nil {
		return *r.publish, nil
	}
	q := r.query.Select("publish")
	q = q.Arg("build", build)

	q = q.Arg("ref", ref)

	q = q.Arg("creds", creds)

	var response string
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type builderImpl struct {
	query *querybuilder.Selection
	id    *dagger.ID
}

func (r *builderImpl) WithGraphQLQuery(q *querybuilder.Selection) Builder {
	return &builderImpl{query: q}
}

func (r *builderImpl) XXX_GraphQLType() string {
	return "ShipwrightBuilder"
}

func (r *builderImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *builderImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *builderImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *builderImpl) UnmarshalJSON(bs []byte) error {
	var id dagger.ID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = builderImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("ShipwrightBuilder")}
	return nil
}

func (r *builderImpl) toIface() Builder {
	if r == nil {
		return nil
	}
	return r
}

func (r *builderImpl) ID(ctx context.Context) (dagger.ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response dagger.ID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *builderImpl) Build(ctx context.Context, source *dagger.Directory) *dagger.Directory {
	q := r.query.Select("build")
	q = q.Arg("source", source)

	return (&dagger.Directory{}).WithGraphQLQuery(q)
}

type deployerImpl struct {
	query  *querybuilder.Selection
	id     *dagger.ID
	deploy *string
}

func (r *deployerImpl) WithGraphQLQuery(q *querybuilder.Selection) Deployer {
	return &deployerImpl{query: q}
}

func (r *deployerImpl) XXX_GraphQLType() string {
	return "ShipwrightDeployer"
}

func (r *deployerImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *deployerImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *deployerImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *deployerImpl) UnmarshalJSON(bs []byte) error {
	var id dagger.ID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = deployerImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("ShipwrightDeployer")}
	return nil
}

func (r *deployerImpl) toIface() Deployer {
	if r == nil {
		return nil
	}
	return r
}

func (r *deployerImpl) ID(ctx context.Context) (dagger.ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response dagger.ID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *deployerImpl) Deploy(ctx context.Context, artifactRef string, environment string, creds *dagger.Secret) (string, error) {
	if r.deploy != nil {
		return *r.deploy, nil
	}
	q := r.query.Select("deploy")
	q = q.Arg("artifactRef", artifactRef)

	q = q.Arg("environment", environment)

	q = q.Arg("creds", creds)

	var response string
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type runnerImpl struct {
	query *querybuilder.Selection
	id    *dagger.ID
}

func (r *runnerImpl) WithGraphQLQuery(q *querybuilder.Selection) Runner {
	return &runnerImpl{query: q}
}

func (r *runnerImpl) XXX_GraphQLType() string {
	return "ShipwrightRunner"
}

func (r *runnerImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *runnerImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *runnerImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *runnerImpl) UnmarshalJSON(bs []byte) error {
	var id dagger.ID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = runnerImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("ShipwrightRunner")}
	return nil
}

func (r *runnerImpl) toIface() Runner {
	if r == nil {
		return nil
	}
	return r
}

func (r *runnerImpl) ID(ctx context.Context) (dagger.ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response dagger.ID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *runnerImpl) Run(ctx context.Context, build *dagger.Directory) *dagger.Container {
	q := r.query.Select("run")
	q = q.Arg("build", build)

	return (&dagger.Container{}).WithGraphQLQuery(q)
}

type testerImpl struct {
	query *querybuilder.Selection
	id    *dagger.ID
}

func (r *testerImpl) WithGraphQLQuery(q *querybuilder.Selection) Tester {
	return &testerImpl{query: q}
}

func (r *testerImpl) XXX_GraphQLType() string {
	return "ShipwrightTester"
}

func (r *testerImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *testerImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *testerImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *testerImpl) UnmarshalJSON(bs []byte) error {
	var id dagger.ID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = testerImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("ShipwrightTester")}
	return nil
}

func (r *testerImpl) toIface() Tester {
	if r == nil {
		return nil
	}
	return r
}

func (r *testerImpl) ID(ctx context.Context) (dagger.ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response dagger.ID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *testerImpl) Test(ctx context.Context, source *dagger.Directory) *dagger.File {
	q := r.query.Select("test")
	q = q.Arg("source", source)

	return (&dagger.File{}).WithGraphQLQuery(q)
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Plan":
		switch fnName {
		case "Execute":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Plan).Execute(&parent, ctx)
		case "WithArtifact":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var a *artifactorImpl
			if inputArgs["a"] != nil {
				err = json.Unmarshal([]byte(inputArgs["a"]), &a)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg a", err))
				}
			}
			var ref string
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			var creds *dagger.Secret
			if inputArgs["creds"] != nil {
				err = json.Unmarshal([]byte(inputArgs["creds"]), &creds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg creds", err))
				}
			}
			return (*Plan).WithArtifact(&parent, a.toIface(), ref, creds), nil
		case "WithBuild":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var b *builderImpl
			if inputArgs["b"] != nil {
				err = json.Unmarshal([]byte(inputArgs["b"]), &b)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg b", err))
				}
			}
			return (*Plan).WithBuild(&parent, b.toIface()), nil
		case "WithDeploy":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var d *deployerImpl
			if inputArgs["d"] != nil {
				err = json.Unmarshal([]byte(inputArgs["d"]), &d)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg d", err))
				}
			}
			var environment string
			if inputArgs["environment"] != nil {
				err = json.Unmarshal([]byte(inputArgs["environment"]), &environment)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg environment", err))
				}
			}
			var creds *dagger.Secret
			if inputArgs["creds"] != nil {
				err = json.Unmarshal([]byte(inputArgs["creds"]), &creds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg creds", err))
				}
			}
			return (*Plan).WithDeploy(&parent, d.toIface(), environment, creds), nil
		case "WithRun":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var r *runnerImpl
			if inputArgs["r"] != nil {
				err = json.Unmarshal([]byte(inputArgs["r"]), &r)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg r", err))
				}
			}
			return (*Plan).WithRun(&parent, r.toIface()), nil
		case "WithTest":
			var parent Plan
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var t *testerImpl
			if inputArgs["t"] != nil {
				err = json.Unmarshal([]byte(inputArgs["t"]), &t)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg t", err))
				}
			}
			return (*Plan).WithTest(&parent, t.toIface()), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Shipwright":
		switch fnName {
		case "ContractVersion":
			var parent Shipwright
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Shipwright).ContractVersion(&parent), nil
		case "Plan":
			var parent Shipwright
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Shipwright).Plan(&parent, source), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
