#!/bin/bash

# bump-go-version-pr.sh - Deliver a completed Go toolchain version bump
# (scripts/gobump, design.md D-9) as a reviewable PR, never a direct push.
#
# Invoked as the LAST step of `make bump-go-version`, after
# `go run ./scripts/gobump -target=$(TARGET)` has already mutated every
# registered site and `make ci-final` has already validated the mutated
# tree in place. This script's only job is git/gh delivery of that already
#-validated diff -- it never mutates a source file itself.
#
# Mirrors this repo's existing precedent for multi-step git/gh automation
# (scripts/changelog-prepend-release.sh, release.yml:597-643): a namespaced
# throwaway branch, an explicit push refspec (never develop/main directly,
# both are PR-protected), and an idempotent `gh pr list` check before
# `gh pr create` so a retried run never opens a duplicate PR.
#
# Usage: ./scripts/bump-go-version-pr.sh <target-version>
# Must run from the repository root, with the target's mutations already
# applied and validated in the working tree.

set -euo pipefail

TARGET="${1:?target version required}"

# --- Repo-root guard (Threat Matrix: git repository selection). Same
# evidence scripts/gobump/main.go's requireRepoRoot uses -- go.work and
# .dagger both present as direct children of cwd -- checked with plain
# filesystem tests, before this script issues a single git or gh command.
if [ ! -f "go.work" ] || [ ! -d ".dagger" ]; then
  echo "::error::must be run from the repository root (go.work and .dagger not found in $(pwd))" >&2
  exit 1
fi

BRANCH="chore/go-${TARGET}"

# --- Clean-worktree precondition (Threat Matrix: commit state). A correct
# gobump run only ever MODIFIES pre-existing, registered files (the
# scripts/gobump/sites registry entries plus the go.work-mediated sites) --
# it never creates a new file. So the presence of ANY untracked ("??")
# entry means something unexpected happened (e.g. GoRuntimeUpgrader's
# incidental .shipwright/ report artifacts, see apply-pr2), and this script
# refuses rather than silently discarding it or -- far worse -- sweeping it
# into the commit with a broad `git add -A`. This is also why the commit
# below is staged one known-modified path at a time instead of `-A`/`-a`:
# unexpected content is refused up front, and everything that IS staged is
# staged by explicit, individually-named path.
UNTRACKED="$(git status --porcelain | grep '^??' || true)"
if [ -n "$UNTRACKED" ]; then
  echo "::error::worktree has untracked files -- refusing to commit an unexpected diff:" >&2
  echo "$UNTRACKED" >&2
  exit 1
fi

# --- Scoped git add: every tracked file the bump modified, one path at a
# time. Never `git add -A` (would also sweep up untracked files, already
# refused above, if this check were ever weakened) and never
# `git commit -a` (implicit, un-auditable scope).
CHANGED_FILES="$(git diff --name-only)"
if [ -z "$CHANGED_FILES" ]; then
  echo "Nothing changed for target ${TARGET} -- already at that version, nothing to commit."
  exit 0
fi

while IFS= read -r file; do
  [ -n "$file" ] && git add -- "$file"
done <<<"$CHANGED_FILES"

git commit -m "chore(go): bump Go toolchain to ${TARGET}"

# --- Push via an explicit throwaway-branch refspec -- never a direct push
# to develop/main (Threat Matrix: push state). Both branches require every
# change to go through a pull request (branch protection with
# enforce_admins:true, same as release.yml:618-625's CHANGELOG PR), so
# there is no ref this script could push a commit onto directly even if it
# tried. `--force` is safe here specifically because chore/go-<target> is a
# namespaced, single-purpose branch this script owns and recreates fresh on
# every run -- never a shared branch.
git push --force origin "HEAD:refs/heads/${BRANCH}"

# --- Idempotent PR (Threat Matrix: PR commands). `$BRANCH` derives only
# from `$TARGET`, which scripts/gobump's own E6 validation
# (^\d+\.\d+\.\d+$) already enforced before any mutation happened -- so
# there is no argument-injection surface here.
EXISTING_PR="$(gh pr list --head "$BRANCH" --base develop --state open --json number --jq '.[0].number')"
if [ -n "$EXISTING_PR" ]; then
  echo "ℹ️ PR #${EXISTING_PR} already open for ${BRANCH} -- branch updated, nothing else to do."
else
  gh pr create \
    --base develop \
    --head "$BRANCH" \
    --title "chore(go): bump Go toolchain to ${TARGET}" \
    --body "Automated Go toolchain bump to ${TARGET}, generated by \`make bump-go-version\` (scripts/gobump). Validated by \`ci-final\` before this PR was opened."
  echo "✅ Opened Go version bump PR for ${TARGET}"
fi
